# Generated by Django 5.2.12 on 2026-03-30 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('complaint_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CFPBComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(blank=True, null=True)),
                ('product', models.CharField(max_length=200)),
                ('sub_product', models.CharField(blank=True, max_length=200)),
                ('issue', models.CharField(blank=True, max_length=300)),
                ('sub_issue', models.CharField(blank=True, max_length=300)),
                ('complaint_narrative', models.TextField(blank=True)),
                ('company', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('submitted_via', models.CharField(blank=True, max_length=50)),
                ('company_response', models.CharField(blank=True, max_length=200)),
                ('timely_response', models.BooleanField(default=False)),
                ('consumer_disputed', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CFPB Complaint',
                'verbose_name_plural': 'CFPB Complaints',
            },
        ),
        migrations.CreateModel(
            name='ComplaintStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('strategy_text', models.TextField()),
                ('success_rate', models.FloatField(default=0.0)),
                ('letter_template', models.TextField(help_text='Template for complaint letter. Use {company}, {product}, {complaint_summary}, {timeframe}, {user_name}, {date} as placeholders.')),
                ('times_used', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='complaints.category')),
            ],
            options={
                'ordering': ['-success_rate'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(help_text='Original complaint text')),
                ('encrypted_personal_data', models.BinaryField(blank=True, null=True)),
                ('category_confidence', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('urgency_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('product', models.CharField(blank=True, max_length=200)),
                ('timeframe', models.CharField(blank=True, max_length=200)),
                ('letter_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predicted_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='complaints.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('matched_strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.complaintstrategy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
