# Generated by Django 5.2.12 on 2026-03-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='letter_file',
            field=models.FileField(blank=True, null=True, upload_to='letters/'),
        ),
    ]
