# Generated by Django 5.2.12 on 2026-03-30 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_letter_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(help_text="Type of company e.g. 'ISP', 'Bank', 'Energy', 'Retailer', 'Airline'", max_length=100)),
                ('issue_type', models.CharField(help_text="e.g. 'Service outage', 'Billing error', 'Faulty product', 'Delayed refund'", max_length=200)),
                ('keywords', models.TextField(blank=True, help_text="Comma-separated keywords for matching e.g. 'broadband,wifi,internet,outage'")),
                ('letter_body', models.TextField(help_text='The full complaint letter body. Use {company}, {product}, {timeframe}, {user_name}, {date} as placeholders for personalisation.')),
                ('source', models.CharField(blank=True, help_text="Where this letter came from e.g. 'Citizens Advice template', 'User provided'", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_letters', to='complaints.category')),
            ],
            options={
                'ordering': ['category', 'issue_type'],
            },
        ),
    ]
